### PR TITLE
onepad: Update controller mappings

### PR DESCRIPTION
**Pull request by kode54**
### Description of Changes
Update controller mappings from upstream, including a personal contribution to macOS mappings

### Rationale behind Changes
Improve controller support, including adding support for previously unmapped controllers

### Suggested Testing Steps
Test the included controllers for functionality.

### CODE REVIEW

**Comment by TellowKrinkle** [comment]
I think you want to be PRing to https://github.com/PCSX2/pcsx2, this master branch just follows that one with minor delays

(And if you meant to PR to the MacOS branch, I'd still recommend targeting PCSX2 master instead for a change like this)

**Comment by kode54** [comment]
Why didn't this email me? Anyway, this is wrong anyway. The real change needed for this particular controller is a newer SDL2, version 2.0.16.

**Comment by TellowKrinkle** [comment]
Ahh in that case, I'll try to remember to update SDL on my build computer before the next release I make

Though people have had luck swapping the dylib out in `PCSX2.app/Contents/Library/Frameworks` in the past

**Comment by kode54** [comment]
Yeah, I had great luck swapping in the libSDL from my own build with up to date Homebrew, into your latest build, and it worked. On the other hand, my build didn't work so hot. Different menus than your build, and it crashes on quit.

You may wish to upload a newer build on GitHub Releases than what is already there, as the release there doesn't have working OpenGL on my M1 Mac mini, while the build from the forum does. Or it seems to.

The build on GitHub also crashes during the first run setup wizard if I attempt to configure the graphics plugin.

**Comment by TellowKrinkle** [comment]
Use the [tag paired with the release](https://github.com/tellowkrinkle/pcsx2/releases/tag/macos-20210327) to get a build that matches the release.  As for the mentioned issues
- Graphics configuration seems to be broken with newer versions of GTK3.  Currently worked around in the released binaries by using GTK2 (`-DGTK2_API=ON` in CMake) and commenting out the DEV9 config code that doesn't work with it (see 56b3eb4317214376b7068fc46acba905c4211208 from the most recent tagged release).  Though it seems to be working again on my dev computer (GTK3 3.24.30 from Homebrew) so... YMMV?  Planned actual solution is to wait for the merge of PCSX2/pcsx2#3642 and drop GTK entirely, it's a massive pain and I really don't want to deal with it.
- Crash on quit is fixed by PCSX2/pcsx2#4666 and will therefore be fixed the next time I rebase the MacOS branch over master

> You may wish to upload a newer build on GitHub Releases than what is already there, as the release there doesn't have working OpenGL on my M1 Mac mini, while the build from the forum does. Or it seems to.

Do you mean the one from GitHub Actions?  The one in releases is what's linked to in the forums.  The software renderer in GH Actions releases won't work on M1 because it needs the unmerged PCSX2/pcsx2#3577, which I haven't rebased since GS merge so it's a bit incompatible at the moment (will fix soon™).  Hardware renderer should work (though I don't have an M1 Mac to test).

**Pull request closed without merging**
